import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { HomeNavbar } from "@/components/nav/HomeNavbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="min-h-screen flex gap-8">
          <HomeNavbar className="h-full" />
          <main>{children}</main>
        </div>
      </body>
    </html>
  );
}
